model:
  type : "ALVIT"
  architecture : {
        "in_channels": 1,
        "base_channels" : 8,
        "num_layers" : 3
  }
---
train:
  epoch: 50
  batch_size: 64
  num_workers: 32
  optimizer: 'AdamW'
  Adam: 0.0001
  AdamW: 0.0001
  adabound:
    initial: 0.001
    final: 0.05
  frame_num: 128
  summary_interval: 50
---
loss:
  type: 'MSELoss'
  mwMSELoss : 
    alpha : 0.9
  wSDRLoss :
    alpha : 0.99
---
scheduler: # Plateau, oneCycle, CosineAnnealingLR
  type: 'Plateau'
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
  CosineAnnealingLR : 
    T_max : 100  # Maximum number of iterations.
    eta_min : 0.000001
---
data:
  root_train : "/home/data/kbh/lip/LRS3/trainval"
  root_test: "/home/data/kbh/lip/LRS3/test"
---
log:
  root: '/home/nas/user/kbh/AE_lip'

